import { expect, Locator, Page } from '@playwright/test';

export class EmployeePage {
  readonly page: Page;

  // Navigation
  readonly pimSideNavLink: Locator;
  readonly topbarEmployeeListLink: Locator;
  readonly topbarAddEmployeeLink: Locator;

  // Employee list / search
  readonly employeeNameSearchInput: Locator;
  readonly employeeIdSearchInput: Locator;
  readonly searchButton: Locator;
  readonly resetButton: Locator;
  readonly tableRows: Locator;
  readonly noRecordsFoundText: Locator;

  // Add employee
  readonly firstNameInput: Locator;
  readonly middleNameInput: Locator;
  readonly lastNameInput: Locator;
  readonly employeeIdInputOnAddForm: Locator;
  readonly saveButton: Locator;
  readonly cancelButton: Locator;

  // Header user menu
  readonly userDropdownTab: Locator;
  readonly logoutMenuItem: Locator;

  constructor(page: Page) {
    this.page = page;

    // Navigation
    this.pimSideNavLink = page.getByRole('link', { name: 'PIM' });
    this.topbarEmployeeListLink = page.getByRole('link', { name: 'Employee List' });
    this.topbarAddEmployeeLink = page.getByRole('link', { name: 'Add Employee' });

    // Search panel
    const searchForm = page.locator('form.oxd-form');
    this.employeeNameSearchInput = searchForm.locator('input[placeholder="Type for hints..."]').first();
    this.employeeIdSearchInput = searchForm.locator('div.oxd-input-group:has(label:has-text("Employee Id")) input');
    this.searchButton = page.getByRole('button', { name: 'Search' });
    this.resetButton = page.getByRole('button', { name: 'Reset' });

    // Table
    this.tableRows = page.locator('.oxd-table-body .oxd-table-row');
    this.noRecordsFoundText = page.getByText('No Records Found');

    // Add employee form
    this.firstNameInput = page.getByRole('textbox', { name: 'First Name' });
    this.middleNameInput = page.getByRole('textbox', { name: 'Middle Name' });
    this.lastNameInput = page.getByRole('textbox', { name: 'Last Name' });
    this.employeeIdInputOnAddForm = page.locator('div.oxd-input-group:has(label:has-text("Employee Id")) input');
    this.saveButton = page.getByRole('button', { name: 'Save' });
    this.cancelButton = page.getByRole('button', { name: 'Cancel' });

    // User dropdown
    this.userDropdownTab = page.locator('.oxd-userdropdown-tab');
    this.logoutMenuItem = page.getByRole('menuitem', { name: 'Logout' });
  }

  async gotoEmployeeList(): Promise<void> {
    await this.page.goto('/web/index.php/pim/viewEmployeeList');
    await expect(this.page).toHaveURL(/\/pim\/viewEmployeeList/);
    await expect(this.page.getByRole('heading', { name: 'Employee Information' })).toBeVisible();
  }

  async gotoAddEmployee(): Promise<void> {
    await this.page.goto('/web/index.php/pim/addEmployee');
    await expect(this.page.getByRole('heading', { name: 'Add Employee' })).toBeVisible();
  }

  async openPimModule(): Promise<void> {
    await this.pimSideNavLink.click();
    // PIM can land on employee list
    await expect(this.page).toHaveURL(/\/pim\//);
  }

  async getAutoGeneratedEmployeeId(): Promise<string> {
    const id = await this.employeeIdInputOnAddForm.inputValue();
    expect(id).toBeTruthy();
    return id;
  }

  async addEmployee(firstName: string, lastName: string): Promise<{ employeeId: string }>{
    await this.firstNameInput.fill(firstName);
    await this.lastNameInput.fill(lastName);
    const employeeId = await this.getAutoGeneratedEmployeeId();
    await this.saveButton.click();
    await expect(this.page).toHaveURL(/\/pim\/viewPersonalDetails/);
    return { employeeId };
  }

  async searchByEmployeeId(employeeId: string): Promise<void> {
    await this.employeeIdSearchInput.fill(employeeId);
    await this.searchButton.click();
    // results load
    await this.page.waitForTimeout(500);
  }

  async searchByEmployeeName(name: string): Promise<void> {
    await this.employeeNameSearchInput.fill(name);
    await this.searchButton.click();
    await this.page.waitForTimeout(500);
  }

  async openFirstSearchResultForEdit(): Promise<void> {
    await expect(this.tableRows.first()).toBeVisible();
    await this.tableRows.first().locator('button:has(i.bi-pencil-fill)').click();
    await expect(this.page).toHaveURL(/\/pim\/viewPersonalDetails/);
  }

  async deleteFirstSearchResultAndConfirm(confirm: boolean): Promise<void> {
    await expect(this.tableRows.first()).toBeVisible();
    await this.tableRows.first().locator('button:has(i.bi-trash)').click();

    const dialog = this.page.locator('.oxd-dialog-container');
    await expect(dialog).toBeVisible();

    if (confirm) {
      await this.page.getByRole('button', { name: /Yes, Delete/i }).click();
    } else {
      await this.page.getByRole('button', { name: /No, Cancel/i }).click();
    }

    await dialog.waitFor({ state: 'hidden', timeout: 10_000 }).catch(() => null);
  }

  async expectNoRecordsFound(): Promise<void> {
    await expect(this.noRecordsFoundText).toBeVisible();
  }

  async logout(): Promise<void> {
    await this.userDropdownTab.click();
    await this.logoutMenuItem.click();
    await expect(this.page).toHaveURL(/\/auth\/login/);
  }

  async updateMiddleNameAndSave(value: string): Promise<void> {
    // Personal Details page - middle name exists
    await expect(this.page.getByRole('heading', { name: 'Personal Details' })).toBeVisible();
    await this.middleNameInput.fill(value);
    // On Personal Details page, there are multiple Save buttons; first corresponds to Personal Details section
    await this.page.getByRole('button', { name: 'Save' }).first().click();
    // best-effort wait for save
    await this.page.waitForTimeout(500);
  }

  async cancelEditingPersonalDetails(expectedValue: string): Promise<void> {
    // There is no explicit cancel on this section in the demo UI.
    // Implemented as: change value, navigate away without saving, then validate original value remains.
    // This method assumes caller already captured original value.
    await this.middleNameInput.fill('TEMP_UNSAVED');
    await this.gotoEmployeeList();
    // reopen same employee is handled in test.
    await expect(this.middleNameInput).toHaveValue(expectedValue);
  }
}
